### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by craig1123** [reach/router#85]
How can one scroll to top of page on each page change?

I'd rather not do a window.scrollTo(0,0) on every route component.... but I will if it comes to it

**Comment by loliver** [comment]
I'm getting the same error, it looks like it occurs when you're referencing a `path` from a `Link to` outside of the `Router` that the `path` is defined in.

I got around this by calling `navigate` rather than using `Link` in a header dropdown menu outside of the `Router`.

**Comment by ryanflorence** [comment]
@loliver Links outside of Router should work just fine, can you post a codesandbox of the problem?

@craig1123 Does your link have a `to` prop defined?

**Comment by ryanflorence** [comment]
(also server side rendering is busted right now because of a bug in React, but will be fixed tomorrow when I cut a new release thanks to #92, so it might be related to that)

**Comment by craig1123** [comment]
Yes, my links have the "to" prop defined. I switched my app from React Router 4 where it was working with server side rendering. I'll wait until that bug is fixed in React to try again. Will keep you updated

**Comment by shaundillon** [comment]
@ryanflorence - Hi there, I see the fix has gone in but a new release hasn't been cut yet, is that waiting on something else or forgotten? Cheers!

**Comment by loganfromlogan** [comment]
I'm getting the same error when using Jest to test a component that has a Link tag. The `to` prop is defined.

**Comment by loganfromlogan** [comment]
If anyone else comes across this, I found that mocking <Link> gets me around this problem.

```javascript
jest.mock("@reach/router", () => ({
  Link: ({ children, to }) => <a href={to}>{children}</a>,
}))
```

**Comment by hefei00** [comment]
The error happened when I run a simple test to the App component.
the error message is:
    TypeError: Cannot read property 'substr' of undefined

      at startsWith (node_modules/@reach/router/lib/utils.js:15:17)
      at node_modules/@reach/router/index.js:480:58
      at LocationProvider.render (node_modules/@reach/router/index.js:151:40)
      at finishClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14301:31)
      at updateClassComponent (node_modules/react-dom/cjs/react-dom.development.js:14264:10)
      at beginWork (node_modules/react-dom/cjs/react-dom.development.js:15082:16)
      at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:17820:12)
      at workLoop (node_modules/react-dom/cjs/react-dom.development.js:17860:24)
      at renderRoot (node_modules/react-dom/cjs/react-dom.development.js:17946:7)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:18837:7)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:18749:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:18723:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:18592:5)
      at scheduleWork (node_modules/react-dom/cjs/react-dom.development.js:18401:5)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:19069:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:19097:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:19154:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:19416:3)
      at node_modules/react-dom/cjs/react-dom.development.js:19556:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:18952:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:19552:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:19613:12)
      at Object.<anonymous>.it (src/App.test.js:7:22)
          at new Promise (<anonymous>)
      at Promise.resolve.then.el (node_modules/p-map/index.js:46:16)
      at process._tickCallback (internal/process/next_tick.js:68:7)

  ✕ renders without crashing (43ms)

the test is:
```js
import React from 'react'
import ReactDOM from 'react-dom'
import App from './App'

it('renders without crashing', () => {
  const div = document.createElement('div')
  ReactDOM.render(<App />, div)
  ReactDOM.unmountComponentAtNode(div)
})
```
the component is:
```js
<div className="container">
        <nav>
          <ul>
            <li>
              <Link to="/">Home</Link>
            </li>
            <li>
              <Link to="/about">About</Link>
            </li>
            <li>
              <Link to="/count">Count</Link>
            </li>
          </ul>
        </nav>
        <hr />
        <Router>
          <Home path="/" />
          <About path="/about" />
          <Count path="/count" />
        </Router>
      </div>
```

**Comment by coderitual** [comment]
Also if it happens when there is a missing `to` prop in a Link component. It might be a good idea to have a better message instead of this.

**Comment by tomasfrancisco** [comment]
This same error also occurs when `Link` is rendered by a `Match` component:

```jsx
<Match path="/my/route">
    {({ match }: MatchRenderProps<{}>) => (
        <Link to="/my-route">Gegevens</Link>
    )}
</Match>
```

**Comment by devdarren7** [comment]
im facing the same issue...can I somehow bypass this and setup my own react routing?

**Comment by gcosgreave-us** [comment]
> Also if it happens when there is a missing `to` prop in a Link component. It might be a good idea to have a better message instead of this.

This should definitely be a warning message, this comment saved me so much time cheers @coderitual 👍🏻
